#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 1. Check for TypeScript errors (The whole project)
echo "🔎 Checking Types..."
npm run type-check

# 2. Lint and Format only the staged files
echo "✨ Linting & Formatting..."
npx lint-staged